version: '3'
services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules/'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development